# permissions for end users to edit contractproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: contractproxy-editor-role
rules:
- apiGroups:
  - kontractdeployer.expedio.xyz
  resources:
  - contractproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kontractdeployer.expedio.xyz
  resources:
  - contractproxies/status
  verbs:
  - get
