# permissions for end users to edit contractversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: contractversion-editor-role
rules:
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - contractversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - contractversions/status
  verbs:
  - get
