# permissions for end users to view contractversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: contractversion-viewer-role
rules:
- apiGroups:
  - kontractdeployer.expedio.xyz
  resources:
  - contractversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kontractdeployer.expedio.xyz
  resources:
  - contractversions/status
  verbs:
  - get
