# permissions for end users to edit proxyadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: proxyadmin-editor-role
rules:
- apiGroups:
  - kontractdeployer.expedio.xyz.expedio.xyz
  resources:
  - proxyadmins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kontractdeployer.expedio.xyz.expedio.xyz
  resources:
  - proxyadmins/status
  verbs:
  - get
