# permissions for end users to view wallets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: wallet-viewer-role
rules:
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - wallets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - wallets/status
  verbs:
  - get
