apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: RPCProvider
metadata:
  name: infura-holesky
spec:
  providerName: Infura
  secretRef:
    name: infura-api-secret
    tokenKey: key
    urlKey: endpoint