---
apiVersion: kontract.expedio.xyz/v1alpha1
kind: RPCProvider
metadata:
  name: infura-holesky
spec:
  providerName: Infura
  secretRef:
    name: infura-holesky-api-secret
    tokenKey: key
    urlKey: endpoint

---
apiVersion: v1
kind: Secret
metadata:
  name: infura-holesky-api-secret
stringData:
  endpoint: https://holesky.infura.io/v3/
  key: ***REMOVED***