---
apiVersion: kontract.expedio.xyz/v1alpha1
kind: RPCProvider
metadata:
  name: infura-amoy
spec:
  providerName: Infura
  secretRef:
    name: infura-amoy-api-secret
    tokenKey: key
    urlKey: endpoint

---
apiVersion: v1
kind: Secret
metadata:
  name: infura-amoy-api-secret
stringData:
  endpoint: https://polygon-amoy.infura.io/v3/
  key: 39f7931f744743f9ace2da189784de4b