apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kontract.fullname" . }}-action-editor-role
  labels:
  {{- include "kontract.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - actions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - actions/status
  verbs:
  - get