apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kontract.fullname" . }}-contract-viewer-role
  labels:
  {{- include "kontract.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - contracts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kontract.expedio.xyz
  resources:
  - contracts/status
  verbs:
  - get