apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: sample-resources
    repoURL: https://github.com/expedio-blockchain/Kontract.git
    targetRevision: demo
  project: default