apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: BlockExplorer
metadata:
  name: blockexplorer-sample
spec:
  explorerName: Etherscan
  secretRef:
    name: etherscan-api-secret
    tokenKey: key
    urlKey: endpoint