apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: Contract
metadata:
  name: foundry-config-contract
spec:
  contractName: FoundryConfigContract
  networkRefs:
   - holesky
  walletRef: dev-wallet
  gasStrategyRef: high-priority-gas
  code: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.9;
    contract FoundryConfigContract {
      uint128 public value;
      function setValue(uint128 newValue) public {
        value = newValue;
      }
    }
  test: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.9;
    import "src/FoundryConfigContract.sol";
    contract FoundryConfigContractTest {
      FoundryConfigContract myContract;
      function setUp() public {
        myContract = new FoundryConfigContract();
      }
      function testInitialValue() public {
        myContract.setValue(1);
      }
    }
  foundryConfigRef:
    name: custom-foundry-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-foundry-config
data:
  foundry.toml: |
    [rpc_endpoints]
    mainnet = "https://eth.llamarpc.com"
    [profile.default]
    src = "src"
    out = "out"
    libs = ["lib"]
    ffi = true
    fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
    solc_version = "0.8.26"
    evm_version = "cancun"
    eth_rpc_url = "https://eth.llamarpc.com"