apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: Contract
metadata:
  name: contract-sample
spec:
  contractName: MySmartContract
  networkRefs:
   - network-sample
  walletRef: wallet-sample
  gasStrategyRef: high-priority-gas
  code: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.0;
    contract MySmartContract {
      uint256 public value;
      function setValue(uint256 newValue) public {
        value = newValue;
      }
    }
  test: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.0;
    import "src/MySmartContract.sol";
    contract MySmartContractTest {
      MySmartContract myContract;
      function setUp() public {
        myContract = new MySmartContract();
      }
      function testInitialValue() public {
        myContract.setValue(1);
      }
    }
