apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: Contract
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: contract-sample
spec:
  contractName: MySmartContract
  networkRef: network-sample
  walletRef: wallet-sample
  gasStrategyRef: high-priority-gas
  code: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.0;
    contract MySmartContract {
      uint256 public value;
      function setValue(uint256 newValue) public {
        value = newValue;
      }
    }
  test: |
    // SPDX-License-Identifier: MIT
    pragma solidity ^0.8.0;
    import "src/MySmartContract.sol";
    contract MySmartContractTest {
      MySmartContract myContract;
      function setUp() public {
        myContract = new MySmartContract();
      }
      function testInitialValue() public {
        myContract.setValue(1);
      }
    }
status:
  contractAddress: 0x...
  deploymentTime: 2024-09-01T00:00:00Z
  transactionHash: 0x...
  test: passed
  state: deployed
