---
apiVersion: kontractdeployer.expedio.xyz/v1alpha1
kind: BlockExplorer
metadata:
  name: etherscan-block-explorer
spec:
  explorerName: etherscan
  secretRef:
    name: etherscan-api-secret
    tokenKey: key
    urlKey: endpoint

---
apiVersion: v1
kind: Secret
metadata:
  name: etherscan-api-secret
type: Opaque
stringData:
  key: UGJ8V9GHANU4GXSFHYUARQCS3AZQ7HYQ3A
  endpoint: https://api.etherscan.io/api