---
apiVersion: kontract.expedio.xyz/v1alpha1
kind: BlockExplorer
metadata:
  name: polygonscan-block-explorer
spec:
  explorerName: polygonscan
  secretRef:
    name: polygonscan-api-secret
    tokenKey: key
    urlKey: endpoint

---
apiVersion: v1
kind: Secret
metadata:
  name: polygonscan-api-secret
stringData:
  key: ***REMOVED***
  endpoint: https://api-amoy.polygonscan.com/api